# name: Generate Snake

# on:
#   schedule:
#     - cron: "0 */12 * * *"
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     env:
#       FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Generate Snake
#         uses: Platane/snk@v3
#         with:
#           github_user_name: khemraj959
#           outputs: dist/snake.svg

#       - name: Deploy Snake
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           branch: output
#           folder: dist
